---

- include_role: name=yourlabs.remember  # get user to tell variables

- name: Set fqdn in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1 (.*)$'
    line: 127.0.0.1 {{ fqdn }} \1
    backrefs: yes
    owner: root
    group: root
    mode: '0644'

- name: Set hostname in /etc/hostname
  copy:
    content: "{{ fqdn.split('.')[0] }}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Remember this role was deployed successfully on this host
  remember:
    extra:
      state: success
